import { Link } from "wouter";
import { SEOHead } from "@/components/SEOHead";
import { Footer } from "@/components/Footer";

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-cream text-text-dark font-sans">
      <SEOHead
        title="Privacy Policy — Bhagavad Gita"
        description="Privacy policy for Bhagavad Gita Sacred Wisdom website. Learn how we handle your data, cookies, and personal information."
        canonical="/privacy"
        keywords="bhagavad gita privacy policy, gita website privacy"
      />

      <nav className="sticky top-0 z-50 bg-dark-brown/95 backdrop-blur border-b border-medium-brown px-4 py-4">
        <div className="max-w-6xl mx-auto flex items-center text-sm font-cinzel text-parchment/70 gap-2">
          <Link href="/" className="hover:text-gold transition-colors">Home</Link>
          <span className="text-gold">›</span>
          <span className="text-gold font-semibold">Privacy Policy</span>
        </div>
      </nav>

      <section className="py-16 px-4 text-center" style={{ background: "linear-gradient(160deg, #1A0A02, #2E1408, #3A1A08)" }}>
        <h1 className="text-4xl md:text-5xl font-cinzel text-white mb-4">Privacy Policy</h1>
        <p className="text-parchment/70 font-serif">Last updated: {new Date().toLocaleDateString("en-IN", { year: "numeric", month: "long", day: "numeric" })}</p>
      </section>

      <main className="max-w-3xl mx-auto px-4 py-16">
        <div className="prose prose-stone max-w-none font-serif text-text-medium leading-relaxed space-y-8">
          {[
            {
              heading: "1. Information We Collect",
              content: `We collect minimal information necessary to provide our services. When you use our AI Oracle feature ("Ask the Gita"), your questions are sent to our AI service to generate responses. We do not permanently store your questions or link them to your identity. When you visit our website, standard server logs may include your IP address, browser type, and pages visited — this is standard practice for all web services.`,
            },
            {
              heading: "2. How We Use Your Information",
              content: `Your questions to the AI Oracle are used solely to generate relevant responses based on Bhagavad Gita teachings. We do not sell, rent, or share your personal information with third parties for marketing purposes. We may use aggregated, anonymized usage statistics to improve our service.`,
            },
            {
              heading: "3. Cookies",
              content: `Our website uses minimal cookies necessary for basic functionality. We do not use tracking cookies for advertising. Your browser settings allow you to control or delete cookies at any time. We use session data to improve your browsing experience on the site.`,
            },
            {
              heading: "4. Third-Party Services",
              content: `We use Anthropic's Claude AI to power our Oracle and verse commentary features. Your questions are processed through this service according to Anthropic's privacy policy. We use Google Fonts for typography — Google may log requests to their font servers. We do not use Google Analytics or Facebook tracking pixels.`,
            },
            {
              heading: "5. Data Retention",
              content: `Verse commentaries generated by our AI are cached in our database to improve loading speed for future visitors. These caches contain only verse content, not user identities or personal information. Questions asked to the Oracle are not permanently stored.`,
            },
            {
              heading: "6. Children's Privacy",
              content: `Our website is suitable for all ages and contains religious and educational content. We do not knowingly collect personal information from children under 13. The Bhagavad Gita's teachings are for all humanity.`,
            },
            {
              heading: "7. Security",
              content: `We use industry-standard security practices to protect our servers and any data we process. Our site is served over HTTPS (SSL encryption) to protect data in transit.`,
            },
            {
              heading: "8. Your Rights",
              content: `You have the right to know what information we hold about you, request deletion of your data, and opt out of any future data collection. Since we collect minimal personal data, there is generally little to request. For any privacy concerns, please contact us through our Contact page.`,
            },
            {
              heading: "9. Changes to This Policy",
              content: `We may update this privacy policy from time to time. We will notify users of significant changes by updating the date at the top of this page. Continued use of our website after changes constitutes acceptance of the updated policy.`,
            },
            {
              heading: "10. Contact",
              content: `For privacy-related inquiries, please visit our Contact page. We are committed to addressing your concerns promptly and transparently.`,
            },
          ].map((section) => (
            <section key={section.heading}>
              <h2 className="font-cinzel text-dark-brown text-xl mb-3">{section.heading}</h2>
              <p>{section.content}</p>
            </section>
          ))}
        </div>

        <div className="mt-12 text-center">
          <Link href="/contact" className="inline-block bg-saffron text-white font-cinzel px-8 py-3 rounded-full hover:bg-deep-saffron transition-colors uppercase tracking-wider text-sm">
            Contact Us →
          </Link>
        </div>
      </main>
      <Footer />
    </div>
  );
}
